SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (
    SELECT F.FISH_TYPE, MAX(F.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO N
    ON F.FISH_TYPE = N.FISH_TYPE
    GROUP BY F.FISH_TYPE
)
ORDER BY F.ID;